#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 0 1 2 3 4

bspc config border_width                2
bspc config bottom_padding              8
bspc config left_padding                8
bspc config right_padding               8
bspc config -m HDMI-1 top_padding       8
bspc config window_gap                  12

bspc config focused_border_color "#ebbcba"
bspc config normal_border_color  "#6e6a86"
bspc config active_border_color  "#6e6a86"
bspc config presel_feedback_color      "#9ccfd8"

bspc config split_ratio          0.5
bspc config borderless_monocle   false
bspc config gapless_monocle      false

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a 'Pesterchum' state=floating

picom &
nitrogen --restore &
~/.config/polybar/launch.sh &
